[package]
name = "codegen"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2021"

[dependencies]
attohttpc = "0.23"
marksman_escape = "0.1"
regex = "1.0"
thiserror = "1.0"

[dependencies.clap]
version = "4.0"
features = ["derive"]
