[package]
name = "codegen"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"

[dependencies]
attohttpc = "0.16"
marksman_escape = "0.1"
regex = "1.0"
structopt = "0.3"
thiserror = "1.0"
